# =============================================================================
# KeyLabLive - THE KEYBOARD'S PROTOCOL
# =============================================================================
#
# DO NOT EDIT THIS FILE TO CONFIGURE THE SCRIPT. Settings live in
# keylab_config.py.
#
# What is in here is not a set of choices. It is a description of how an
# Arturia KeyLab mk3 actually behaves, worked out with a MIDI monitor against
# real hardware. Changing a number here does not reconfigure anything; it
# stops the screen working, usually silently.
#
# Full documentation of the protocol, including how it was measured:
# https://github.com/saxofonbrian/keylab-mk3-sysex
#
# -----------------------------------------------------------------------------
# THE SINGLE MOST IMPORTANT THING
# -----------------------------------------------------------------------------
# The keyboard has two separate worlds: Arturia mode (what Analog Lab uses) and
# DAW mode. They use different SysEx families AND different CC numbers, and
# packets meant for one are ignored while the other is displayed. This script
# speaks DAW mode only.
#
# Switch with the physical keys: Prog + screen button 6.
# (Prog + screen button 5 goes back to Arturia mode.)
#
# There is no SysEx that changes the mode. The connect handshake below is sent
# at startup, but it only does anything if the unit is ALREADY in DAW mode. It
# is a handshake, not a mode switch.
#
# How to tell which mode you are in: in DAW mode the screen buttons send
# CC 45-52. In Arturia mode the same buttons send CC 56-63.
# =============================================================================

from __future__ import absolute_import, print_function, unicode_literals

from .keylab_config import LABEL_MAX_LEN

# ===== SysEx envelope =========================================================
# Every packet is HEADER + payload + FOOTER.
SYSEX_HEADER = (0xF0, 0x00, 0x20, 0x6B, 0x7F, 0x42)
SYSEX_FOOTER = (0xF7,)

# Sent at startup. Does nothing unless the keyboard is already in DAW mode.
DAW_CONNECT = SYSEX_HEADER + (0x00, 0x02, 0x05, 0x01) + SYSEX_FOOTER
DAW_DISCONNECT = SYSEX_HEADER + (0x00, 0x02, 0x05, 0x00) + SYSEX_FOOTER

# Packet families:
#   00 02 03   single LED, RGB
#   00 02 04   everything on the screen - buttons, popups, lists
#   00 02 05   connect / disconnect handshake
#
# There is a second family, 00 01 04, which is Analog Lab's own (it works in
# Arturia mode without Analog Lab running). It has its own 7-line list widget
# too, but the 0x28+0x15 list below, in THIS family, already gives 7 full
# lines without costing the top button row, so there is no reason to leave
# this family for the list.
LED_FAMILY = (0x00, 0x02, 0x03)
SCREEN_FAMILY = (0x00, 0x02, 0x04)


# ===== MIDI ===================================================================
# Everything the keyboard sends in DAW mode is on MIDI channel 1, EXCEPT the
# pads, which are on channel 10. Both are 0-indexed here, because that is what
# Live's framework expects.
MAIN_CHANNEL = 0
PAD_CHANNEL = 9


# ===== Screen buttons =========================================================
# They form one unbroken CC range, but the numbering runs the OTHER WAY from the ids: the top row has the
# LOWER CC numbers. Read the table, do not calculate.
#
#   Button  Row     Footer id   CC
#   1       bottom  0x01        49
#   2       bottom  0x02        50
#   3       bottom  0x03        51
#   4       bottom  0x04        52
#   5       top     0x05        45
#   6       top     0x06        46
#   7       top     0x07        47
#   8       top     0x08        48
#
# Lighting a button in the top row costs the locator list nothing: tracks 5-8
# use these buttons exactly like 1-4, full seven-line list throughout.
#
# These buttons do have RGB LEDs, but they have no address in the LED family.
# Their light comes from the colour field of the footer packet itself, which
# is why _footer_packet takes a colour.
SCREEN_BUTTONS = {
    1: (0x01, 49), 2: (0x02, 50), 3: (0x03, 51), 4: (0x04, 52),
    5: (0x05, 45), 6: (0x06, 46), 7: (0x07, 47), 8: (0x08, 48),
}


# ===== Transport row ==========================================================
# Physical order, left to right: Tap, Rec, Play, Stop, Cycle, Back, Forward,
# Metro, Redo, Undo, Quantize, Save.
#
# The row splits into two groups and the second runs BACKWARDS. The first eight
# ascend across CC 20-27; the last four sit at 41-44 and descend relative to
# their physical position. Read the table.
#
#   Button     CC    LED id
#   Tap        23    4
#   Rec        22    5
#   Play       21    6
#   Stop       20    7
#   Cycle      24    8
#   Back       25    9
#   Forward    26    10
#   Metro      27    11
#
# The LED ids follow "physical position + 3".
STOP_CC, STOP_LED = 20, 7
PLAY_CC, PLAY_LED = 21, 6
CYCLE_CC, CYCLE_LED = 24, 8
BACK_CC, BACK_LED = 25, 9
FORWARD_CC, FORWARD_LED = 26, 10

# Tap and Metro flank the row and are the only two buttons in it this script
# does not otherwise use, which is why the chapter switches sit there.
TAP_CC, TAP_LED = 23, 4
METRO_CC, METRO_LED = 27, 11

# Record - Arrangement Record, or the shift key for the clip-launch grid when
# that is switched on. See _Record in keylab_live.py.
REC_CC, REC_LED = 22, 5

# Save, Quantize, Undo, Redo - the second group at the end of the row,
# descending relative to their physical position (see the note above).
#
# Read out of Arturia's own compiled script (KeyLab_mk3/midi.py,
# BUTTON_ID_TO_SYSEX_ID). In that script CC 41 is called "Save_Button" but
# mapped to the role "capture_midi" - this is the MIDI-capture button, not a
# generic save.
SAVE_CC, SAVE_LED = 41, 15
QUANTIZE_CC, QUANTIZE_LED = 42, 14
UNDO_CC, UNDO_LED = 43, 13
REDO_CC, REDO_LED = 44, 12


# ===== Jog wheel ==============================================================
# The wheel is NOT a relative +1/-1 encoder. It sends a value centred on 64,
# and the value moves further from 64 the faster you turn, saturating at 61 and
# 67. Using only the sign, and treating every message as one step, is what
# keeps a list from running away on a fast turn.
WHEEL_CC = 116
WHEEL_CLICK_CC = 117
WHEEL_CENTRE = 64


# ===== Faders =================================================================
# Every fader has TWO CCs: one for movement and one for touch. They sit far
# apart and the touch range is not contiguous - "CC 28 plus the fader number"
# is wrong from fader 5 onwards.
#
#   Fader     1    2    3    4    5    6    7    8    9
#   Movement  105  106  107  108  109  110  111  112  113
#   Touch     28   29   30   31   33   34   35   36   37      (32 is unused)
FADER_VALUE_CCS = (105, 106, 107, 108, 109, 110, 111, 112, 113)
FADER_TOUCH_CCS = (28, 29, 30, 31, 33, 34, 35, 36, 37)

# The keyboard's own on-screen readout for faders is triggered by CAPACITIVE
# SKIN CONTACT, not by the value changing. Put paper between finger and fader,
# or nudge it with a fingernail, and you get no touch CC and no readout at all
# - while the value CC is still sent and the sound still follows.


# ===== Pads ===================================================================
# In the DAW bank the pads send NOTES 0-11 for pads 1-12 on channel 10, note-on
# when pressed and note-off when released. They do NOT send CC.
#
# The other pad banks send entirely different notes out of the PHYSICAL MIDI
# port, not the DAW port, so they are invisible to this script.
PAD_COUNT = 12
PAD_FIRST_NOTE = 0

# LED id = 82 + pad number - 1, i.e. 82-93 for pads 1-12.
PAD_LED_FIRST = 82


# ===== Screen layouts =========================================================
# Layout 0x1D (the fader popup) only DRAWS while a finger is on a fader or
# encoder. That is the capacitive sensor in the hardware, not a rule in the
# protocol: sent with nothing touched - at startup, say - the packet goes out
# and nothing appears. It is useless for text the script wants to raise on its own, and perfectly
# good for text that belongs under a finger. See fader_packet.
#
# Layout 0x1E (the pad popup) draws whenever it is sent, so it carries every
# message the script raises by itself.
FADER_LAYOUT = 0x1D     # draws only under a real finger - see fader_packet
POPUP_LAYOUT = 0x1E     # software-controllable

# The list in the middle of the screen: 7 visible lines, and the cursor is
# anchored on the 4th (0-indexed 3). See list_top and list_cursor_packet.
LIST_VISIBLE_LINES = 7
LIST_ANCHOR = 3
LIST_TITLE = 0x28       # sets the title AND the list length
LIST_APPEND = 0x15      # push a line in at the bottom
LIST_PREPEND = 0x16     # push a line in at the top

# Sending a 0x28 title packet with no lines after it RESETS the list. There is
# no "close list" command; this is the closest thing to one.


# ===== Text ===================================================================
# Plain ASCII 32-126 only. Anything else costs you the character or the whole
# packet, so Danish letters are folded rather than sent.
_ASCII_MAP = {
    "æ": "ae", "ø": "oe", "å": "aa",
    "Æ": "Ae", "Ø": "Oe", "Å": "Aa",
    "é": "e", "è": "e", "ê": "e", "É": "E", "ü": "u", "ö": "o", "ä": "a",
    "–": "-", "—": "-",
    "’": "'", "‘": "'", "“": '"', "”": '"',
}


def to_ascii(text):
    """Text as bytes the screen will accept. Anything unmappable is dropped."""
    out = []
    for ch in (text or ""):
        for c in _ASCII_MAP.get(ch, ch):
            code = ord(c)
            if 32 <= code < 127:
                out.append(code)
    return out


def _len_bytes(n):
    """A 14-bit number as two 7-bit bytes. MIDI cannot carry the 8th bit."""
    n = n & 0x3FFF
    return ((n >> 7) & 0x7F, n & 0x7F)


# ===== Packet builders ========================================================
#
# Three things that are easy to get wrong and hard to diagnose:
#
#  - Send each packet as ONE complete message. Sending it byte by byte for the
#    port to reassemble loses 2-4% of packets, which shows up as "every
#    thirtieth press the screen doesn't update".
#  - Two screen packets sent back to back can race on the device and one is
#    dropped. This script sends them through Live's own MIDI output, which
#    paces them; if you rebuild this for Max, space them out yourself.
#  - ASCII only. See to_ascii above.


def footer_packet(footer_id, lit, label, colour):
    """
    One screen button: its label, its colour and whether it reads as active.

    Field 00 is 0x03 lit / 0x02 unlit, field 03 must be present even though it
    is always zero, field 04 is the colour, field 05 is the text.
    """
    text = tuple(to_ascii(label[:LABEL_MAX_LEN]))
    body = (
        footer_id,
        0x00, (0x03 if lit else 0x02), 0x00,
        0x03, 0x00, 0x00,
        0x04,
    ) + tuple(colour) + (0x00, 0x05) + text + (0x00,)
    return SYSEX_HEADER + SCREEN_FAMILY + body + SYSEX_FOOTER


def popup_packet(value_text, name, hw_value=0):
    """
    A message in the middle of the screen. Uses layout 0x1E, which is the one
    that works without anybody touching the hardware.
    """
    body = (
        POPUP_LAYOUT, 0x00,
    ) + tuple(to_ascii(value_text)) + (0x00, 0x01) \
      + tuple(to_ascii(name[:LABEL_MAX_LEN])) + (
        0x00, 0x02, hw_value, 0x00, 0x04, 0x7F, 0x7F, 0x7F, 0x00
    )
    return SYSEX_HEADER + SCREEN_FAMILY + body + SYSEX_FOOTER


def fader_packet(value_text, name, position, colour):
    """
    The readout that appears under your finger while you move a fader.

    The field order:

        00 02 04 1D | 00 "-6.912 dB" 00 | 01 "Volume" 00 | 02 55 00
                    | 04 00 6C 7A 00

    This only appears while the fader is actually being touched - see the note
    on FADER_LAYOUT above - which is exactly when it is wanted. The keyboard
    draws its own readout from the hardware at the same moment; this packet is
    what puts the DAW's own value there instead.

    position is 0-127 and draws the bar.
    """
    body = (
        FADER_LAYOUT, 0x00,
    ) + tuple(to_ascii(value_text)) + (0x00, 0x01) \
      + tuple(to_ascii(name[:LABEL_MAX_LEN])) + (
        0x00, 0x02, max(0, min(127, int(position))), 0x00, 0x04,
    ) + tuple(colour) + (0x00,)
    return SYSEX_HEADER + SCREEN_FAMILY + body + SYSEX_FOOTER


def list_top(index, length):
    """
    Which line sits at the top of the screen when the cursor is on `index`.
    Every list uses this, on opening and on every move, so the window is
    always the one the firmware expects.
    """
    return max(0, min(index - LIST_ANCHOR, length - LIST_VISIBLE_LINES))


def list_title_packet(title, length):
    """Opens a list. The length tells the firmware how to frame the cursor."""
    hi, lo = _len_bytes(length)
    body = (LIST_TITLE, 0x00) + tuple(to_ascii(title)) + (0x00, 0x02, hi, lo, 0x00)
    return SYSEX_HEADER + SCREEN_FAMILY + body + SYSEX_FOOTER


def list_item_packet(control_byte, text, index):
    """
    One line. control_byte is LIST_APPEND or LIST_PREPEND. index is the
    line's own position in the whole list, counted from 0.

    This is the 0x28+0x15 list, in the 00 02 04 family - the same one the
    footer, popup and fader packets use.
    """
    hi, lo = _len_bytes(index)
    body = (control_byte, 0x00) + tuple(to_ascii(text)) + (
        0x00, 0x02, 0x00, 0x00, 0x03, hi, lo, 0x00)
    return SYSEX_HEADER + SCREEN_FAMILY + body + SYSEX_FOOTER


def list_cursor_packet(index):
    """
    Moves the cursor box without redrawing the lines. index is the plain
    position in the whole list, counted from 0 - the same number Analog Lab
    sends, and what makes the scroll marker move for every single line.

    The firmware places the box itself from that number: on the 4th line,
    except near either end of the list, where the box walks out to the edge.
    So the seven lines on screen have to be the ones list_top() says.
    """
    hi, lo = _len_bytes(index)
    return SYSEX_HEADER + SCREEN_FAMILY + (LIST_APPEND, 0x03, hi, lo, 0x00) + SYSEX_FOOTER


def led_packet(led_id, colour):
    """One LED. RGB, 0-127 per channel. No effect on the screen."""
    return SYSEX_HEADER + LED_FAMILY + (led_id,) + tuple(colour) + (0x00,) + SYSEX_FOOTER


def pad_led_packet(pad_index, colour):
    """pad_index is 0-11."""
    return led_packet(PAD_LED_FIRST + pad_index, colour)


def rgb_from_color_value(value):
    """
    Any of Live's 0xRRGGBB colour integers (a track's, a clip's, a clip
    slot's), converted to the keyboard's 0-127-per-channel RGB. Returns None
    if value is not a usable colour, so callers can fall back to a fixed
    colour instead of drawing black.

    Live stores 0-255 per channel; the KeyLab wants 0-127, hence the halving.
    """
    try:
        value = int(value)
    except (TypeError, ValueError):
        return None
    return ((value >> 16) & 0xFF) // 2, ((value >> 8) & 0xFF) // 2, (value & 0xFF) // 2


def track_colour(track, armed, dim_factor):
    """
    Live's own track colour, converted for the keyboard.

    An un-armed track is dimmed further but never taken fully dark - an unlit
    button on a dark stage is worse than a wrong one.
    """
    try:
        value = int(track.color)
    except (AttributeError, RuntimeError, TypeError, ValueError):
        return None
    rgb = rgb_from_color_value(value)
    if rgb is None:
        return None
    if armed:
        return rgb
    return tuple(max(1, c // dim_factor) for c in rgb)
